// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/mirukentypes; DO NOT EDIT.

package test

import "github.com/miruken-go/miruken"
import "reflect"

var HandlerTestTypes = []reflect.Type{
	miruken.TypeOf[*UserHandler](),
}

